// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

// parserState returns the parser state from the global state map
func parserState(c *current) *ParserState {
	return c.globalStore["state"].(*ParserState)
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Root",
			pos:  position{line: 11, col: 1, offset: 254},
			expr: &choiceExpr{
				pos: position{line: 11, col: 9, offset: 262},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 11, col: 9, offset: 262},
						name: "SlashDelimited",
					},
					&ruleRefExpr{
						pos:  position{line: 11, col: 26, offset: 279},
						name: "PlainRegexp",
					},
				},
			},
		},
		{
			name: "SlashDelimited",
			pos:  position{line: 14, col: 1, offset: 334},
			expr: &actionExpr{
				pos: position{line: 14, col: 19, offset: 352},
				run: (*parser).callonSlashDelimited1,
				expr: &seqExpr{
					pos: position{line: 14, col: 19, offset: 352},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 14, col: 19, offset: 352},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
						&labeledExpr{
							pos:   position{line: 14, col: 23, offset: 356},
							label: "regexp",
							expr: &ruleRefExpr{
								pos:  position{line: 14, col: 30, offset: 363},
								name: "Regexp",
							},
						},
						&litMatcher{
							pos:        position{line: 14, col: 37, offset: 370},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
						&labeledExpr{
							pos:   position{line: 14, col: 41, offset: 374},
							label: "flags",
							expr: &zeroOrOneExpr{
								pos: position{line: 14, col: 47, offset: 380},
								expr: &ruleRefExpr{
									pos:  position{line: 14, col: 47, offset: 380},
									name: "Flags",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 14, col: 54, offset: 387},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "PlainRegexp",
			pos:  position{line: 23, col: 1, offset: 537},
			expr: &actionExpr{
				pos: position{line: 23, col: 16, offset: 552},
				run: (*parser).callonPlainRegexp1,
				expr: &seqExpr{
					pos: position{line: 23, col: 16, offset: 552},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 23, col: 16, offset: 552},
							label: "regexp",
							expr: &ruleRefExpr{
								pos:  position{line: 23, col: 23, offset: 559},
								name: "Regexp",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 23, col: 30, offset: 566},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Flags",
			pos:  position{line: 28, col: 1, offset: 649},
			expr: &actionExpr{
				pos: position{line: 28, col: 10, offset: 658},
				run: (*parser).callonFlags1,
				expr: &oneOrMoreExpr{
					pos: position{line: 28, col: 10, offset: 658},
					expr: &charClassMatcher{
						pos:        position{line: 28, col: 10, offset: 658},
						val:        "[dimgsuy]",
						chars:      []rune{'d', 'i', 'm', 'g', 's', 'u', 'y'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Regexp",
			pos:  position{line: 33, col: 1, offset: 756},
			expr: &actionExpr{
				pos: position{line: 33, col: 11, offset: 766},
				run: (*parser).callonRegexp1,
				expr: &seqExpr{
					pos: position{line: 33, col: 11, offset: 766},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 33, col: 11, offset: 766},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 33, col: 17, offset: 772},
								name: "Match",
							},
						},
						&labeledExpr{
							pos:   position{line: 33, col: 23, offset: 778},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 33, col: 28, offset: 783},
								expr: &seqExpr{
									pos: position{line: 33, col: 30, offset: 785},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 33, col: 30, offset: 785},
											val:        "|",
											ignoreCase: false,
											want:       "\"|\"",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 34, offset: 789},
											name: "Match",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Match",
			pos:  position{line: 45, col: 1, offset: 1085},
			expr: &actionExpr{
				pos: position{line: 45, col: 10, offset: 1094},
				run: (*parser).callonMatch1,
				expr: &labeledExpr{
					pos:   position{line: 45, col: 10, offset: 1094},
					label: "frags",
					expr: &zeroOrMoreExpr{
						pos: position{line: 45, col: 16, offset: 1100},
						expr: &ruleRefExpr{
							pos:  position{line: 45, col: 16, offset: 1100},
							name: "MatchFragment",
						},
					},
				},
			},
		},
		{
			name: "MatchFragment",
			pos:  position{line: 56, col: 1, offset: 1392},
			expr: &actionExpr{
				pos: position{line: 56, col: 18, offset: 1409},
				run: (*parser).callonMatchFragment1,
				expr: &seqExpr{
					pos: position{line: 56, col: 18, offset: 1409},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 56, col: 18, offset: 1409},
							label: "content",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 26, offset: 1417},
								name: "Content",
							},
						},
						&labeledExpr{
							pos:   position{line: 56, col: 34, offset: 1425},
							label: "repeat",
							expr: &zeroOrOneExpr{
								pos: position{line: 56, col: 41, offset: 1432},
								expr: &ruleRefExpr{
									pos:  position{line: 56, col: 41, offset: 1432},
									name: "Repeat",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Content",
			pos:  position{line: 65, col: 1, offset: 1630},
			expr: &choiceExpr{
				pos: position{line: 65, col: 12, offset: 1641},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 65, col: 12, offset: 1641},
						name: "Anchor",
					},
					&ruleRefExpr{
						pos:  position{line: 65, col: 21, offset: 1650},
						name: "Subexp",
					},
					&ruleRefExpr{
						pos:  position{line: 65, col: 30, offset: 1659},
						name: "Charset",
					},
					&ruleRefExpr{
						pos:  position{line: 65, col: 40, offset: 1669},
						name: "Terminal",
					},
				},
			},
		},
		{
			name: "Anchor",
			pos:  position{line: 68, col: 1, offset: 1697},
			expr: &actionExpr{
				pos: position{line: 68, col: 11, offset: 1707},
				run: (*parser).callonAnchor1,
				expr: &choiceExpr{
					pos: position{line: 68, col: 13, offset: 1709},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 68, col: 13, offset: 1709},
							val:        "^",
							ignoreCase: false,
							want:       "\"^\"",
						},
						&litMatcher{
							pos:        position{line: 68, col: 19, offset: 1715},
							val:        "$",
							ignoreCase: false,
							want:       "\"$\"",
						},
					},
				},
			},
		},
		{
			name: "Subexp",
			pos:  position{line: 77, col: 1, offset: 1908},
			expr: &actionExpr{
				pos: position{line: 77, col: 11, offset: 1918},
				run: (*parser).callonSubexp1,
				expr: &seqExpr{
					pos: position{line: 77, col: 11, offset: 1918},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 77, col: 11, offset: 1918},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&labeledExpr{
							pos:   position{line: 77, col: 15, offset: 1922},
							label: "groupType",
							expr: &zeroOrOneExpr{
								pos: position{line: 77, col: 25, offset: 1932},
								expr: &ruleRefExpr{
									pos:  position{line: 77, col: 25, offset: 1932},
									name: "GroupType",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 77, col: 36, offset: 1943},
							label: "regexp",
							expr: &ruleRefExpr{
								pos:  position{line: 77, col: 43, offset: 1950},
								name: "Regexp",
							},
						},
						&litMatcher{
							pos:        position{line: 77, col: 50, offset: 1957},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "GroupType",
			pos:  position{line: 100, col: 1, offset: 2692},
			expr: &choiceExpr{
				pos: position{line: 100, col: 14, offset: 2705},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 100, col: 14, offset: 2705},
						run: (*parser).callonGroupType2,
						expr: &litMatcher{
							pos:        position{line: 100, col: 14, offset: 2705},
							val:        "?:",
							ignoreCase: false,
							want:       "\"?:\"",
						},
					},
					&actionExpr{
						pos: position{line: 101, col: 13, offset: 2752},
						run: (*parser).callonGroupType4,
						expr: &litMatcher{
							pos:        position{line: 101, col: 13, offset: 2752},
							val:        "?=",
							ignoreCase: false,
							want:       "\"?=\"",
						},
					},
					&actionExpr{
						pos: position{line: 102, col: 13, offset: 2806},
						run: (*parser).callonGroupType6,
						expr: &litMatcher{
							pos:        position{line: 102, col: 13, offset: 2806},
							val:        "?!",
							ignoreCase: false,
							want:       "\"?!\"",
						},
					},
					&actionExpr{
						pos: position{line: 103, col: 13, offset: 2860},
						run: (*parser).callonGroupType8,
						expr: &litMatcher{
							pos:        position{line: 103, col: 13, offset: 2860},
							val:        "?<=",
							ignoreCase: false,
							want:       "\"?<=\"",
						},
					},
					&actionExpr{
						pos: position{line: 104, col: 13, offset: 2916},
						run: (*parser).callonGroupType10,
						expr: &litMatcher{
							pos:        position{line: 104, col: 13, offset: 2916},
							val:        "?<!",
							ignoreCase: false,
							want:       "\"?<!\"",
						},
					},
					&actionExpr{
						pos: position{line: 105, col: 13, offset: 2972},
						run: (*parser).callonGroupType12,
						expr: &seqExpr{
							pos: position{line: 105, col: 13, offset: 2972},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 105, col: 13, offset: 2972},
									val:        "?<",
									ignoreCase: false,
									want:       "\"?<\"",
								},
								&labeledExpr{
									pos:   position{line: 105, col: 18, offset: 2977},
									label: "name",
									expr: &ruleRefExpr{
										pos:  position{line: 105, col: 23, offset: 2982},
										name: "GroupName",
									},
								},
								&litMatcher{
									pos:        position{line: 105, col: 33, offset: 2992},
									val:        ">",
									ignoreCase: false,
									want:       "\">\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "GroupName",
			pos:  position{line: 110, col: 1, offset: 3213},
			expr: &actionExpr{
				pos: position{line: 110, col: 14, offset: 3226},
				run: (*parser).callonGroupName1,
				expr: &seqExpr{
					pos: position{line: 110, col: 14, offset: 3226},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 110, col: 14, offset: 3226},
							val:        "[a-zA-Z_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 110, col: 23, offset: 3235},
							expr: &charClassMatcher{
								pos:        position{line: 110, col: 23, offset: 3235},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Charset",
			pos:  position{line: 115, col: 1, offset: 3313},
			expr: &actionExpr{
				pos: position{line: 115, col: 12, offset: 3324},
				run: (*parser).callonCharset1,
				expr: &seqExpr{
					pos: position{line: 115, col: 12, offset: 3324},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 115, col: 12, offset: 3324},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&labeledExpr{
							pos:   position{line: 115, col: 16, offset: 3328},
							label: "inverted",
							expr: &zeroOrOneExpr{
								pos: position{line: 115, col: 25, offset: 3337},
								expr: &litMatcher{
									pos:        position{line: 115, col: 25, offset: 3337},
									val:        "^",
									ignoreCase: false,
									want:       "\"^\"",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 115, col: 30, offset: 3342},
							label: "items",
							expr: &zeroOrMoreExpr{
								pos: position{line: 115, col: 36, offset: 3348},
								expr: &ruleRefExpr{
									pos:  position{line: 115, col: 36, offset: 3348},
									name: "CharsetItem",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 115, col: 49, offset: 3361},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "CharsetItem",
			pos:  position{line: 129, col: 1, offset: 3697},
			expr: &choiceExpr{
				pos: position{line: 129, col: 16, offset: 3712},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 129, col: 16, offset: 3712},
						name: "CharsetRange",
					},
					&ruleRefExpr{
						pos:  position{line: 129, col: 31, offset: 3727},
						name: "CharsetEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 129, col: 47, offset: 3743},
						name: "CharsetLiteral",
					},
				},
			},
		},
		{
			name: "CharsetRange",
			pos:  position{line: 132, col: 1, offset: 3780},
			expr: &actionExpr{
				pos: position{line: 132, col: 17, offset: 3796},
				run: (*parser).callonCharsetRange1,
				expr: &seqExpr{
					pos: position{line: 132, col: 17, offset: 3796},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 132, col: 17, offset: 3796},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 132, col: 23, offset: 3802},
								name: "CharsetRangeBound",
							},
						},
						&litMatcher{
							pos:        position{line: 132, col: 41, offset: 3820},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
						&labeledExpr{
							pos:   position{line: 132, col: 45, offset: 3824},
							label: "last",
							expr: &ruleRefExpr{
								pos:  position{line: 132, col: 50, offset: 3829},
								name: "CharsetRangeBound",
							},
						},
					},
				},
			},
		},
		{
			name: "CharsetRangeBound",
			pos:  position{line: 140, col: 1, offset: 4001},
			expr: &choiceExpr{
				pos: position{line: 140, col: 22, offset: 4022},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 140, col: 22, offset: 4022},
						name: "CharsetRangeEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 140, col: 43, offset: 4043},
						name: "CharsetRangeLiteral",
					},
				},
			},
		},
		{
			name: "CharsetRangeEscape",
			pos:  position{line: 143, col: 1, offset: 4126},
			expr: &choiceExpr{
				pos: position{line: 143, col: 23, offset: 4148},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 143, col: 23, offset: 4148},
						run: (*parser).callonCharsetRangeEscape2,
						expr: &seqExpr{
							pos: position{line: 143, col: 23, offset: 4148},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 143, col: 23, offset: 4148},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&charClassMatcher{
									pos:        position{line: 143, col: 28, offset: 4153},
									val:        "[bfnrtv]",
									chars:      []rune{'b', 'f', 'n', 'r', 't', 'v'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 145, col: 5, offset: 4199},
						run: (*parser).callonCharsetRangeEscape6,
						expr: &seqExpr{
							pos: position{line: 145, col: 5, offset: 4199},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 145, col: 5, offset: 4199},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 145, col: 10, offset: 4204},
									val:        "x",
									ignoreCase: false,
									want:       "\"x\"",
								},
								&charClassMatcher{
									pos:        position{line: 145, col: 14, offset: 4208},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 145, col: 26, offset: 4220},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 147, col: 5, offset: 4269},
						run: (*parser).callonCharsetRangeEscape12,
						expr: &seqExpr{
							pos: position{line: 147, col: 5, offset: 4269},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 147, col: 5, offset: 4269},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 147, col: 10, offset: 4274},
									val:        "u",
									ignoreCase: false,
									want:       "\"u\"",
								},
								&litMatcher{
									pos:        position{line: 147, col: 14, offset: 4278},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&oneOrMoreExpr{
									pos: position{line: 147, col: 18, offset: 4282},
									expr: &charClassMatcher{
										pos:        position{line: 147, col: 18, offset: 4282},
										val:        "[0-9a-fA-F]",
										ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&litMatcher{
									pos:        position{line: 147, col: 31, offset: 4295},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 150, col: 5, offset: 4381},
						run: (*parser).callonCharsetRangeEscape20,
						expr: &seqExpr{
							pos: position{line: 150, col: 5, offset: 4381},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 150, col: 5, offset: 4381},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 150, col: 10, offset: 4386},
									val:        "u",
									ignoreCase: false,
									want:       "\"u\"",
								},
								&charClassMatcher{
									pos:        position{line: 150, col: 14, offset: 4390},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 150, col: 26, offset: 4402},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 150, col: 38, offset: 4414},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 150, col: 50, offset: 4426},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 152, col: 5, offset: 4475},
						run: (*parser).callonCharsetRangeEscape28,
						expr: &seqExpr{
							pos: position{line: 152, col: 5, offset: 4475},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 152, col: 5, offset: 4475},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 152, col: 10, offset: 4480},
									val:        "0",
									ignoreCase: false,
									want:       "\"0\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 152, col: 14, offset: 4484},
									expr: &charClassMatcher{
										pos:        position{line: 152, col: 14, offset: 4484},
										val:        "[0-7]",
										ranges:     []rune{'0', '7'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 154, col: 5, offset: 4528},
						run: (*parser).callonCharsetRangeEscape34,
						expr: &seqExpr{
							pos: position{line: 154, col: 5, offset: 4528},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 154, col: 5, offset: 4528},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 154, col: 10, offset: 4533},
									val:        "c",
									ignoreCase: false,
									want:       "\"c\"",
								},
								&charClassMatcher{
									pos:        position{line: 154, col: 14, offset: 4537},
									val:        "[a-zA-Z]",
									ranges:     []rune{'a', 'z', 'A', 'Z'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CharsetRangeLiteral",
			pos:  position{line: 159, col: 1, offset: 4656},
			expr: &choiceExpr{
				pos: position{line: 159, col: 24, offset: 4679},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 159, col: 24, offset: 4679},
						run: (*parser).callonCharsetRangeLiteral2,
						expr: &charClassMatcher{
							pos:        position{line: 159, col: 24, offset: 4679},
							val:        "[^-\\]\\\\]",
							chars:      []rune{'-', ']', '\\'},
							ignoreCase: false,
							inverted:   true,
						},
					},
					&actionExpr{
						pos: position{line: 161, col: 5, offset: 4725},
						run: (*parser).callonCharsetRangeLiteral4,
						expr: &seqExpr{
							pos: position{line: 161, col: 5, offset: 4725},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 161, col: 5, offset: 4725},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&anyMatcher{
									line: 161, col: 10, offset: 4730,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CharsetEscape",
			pos:  position{line: 166, col: 1, offset: 4813},
			expr: &choiceExpr{
				pos: position{line: 166, col: 18, offset: 4830},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 166, col: 18, offset: 4830},
						run: (*parser).callonCharsetEscape2,
						expr: &seqExpr{
							pos: position{line: 166, col: 18, offset: 4830},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 166, col: 18, offset: 4830},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&labeledExpr{
									pos:   position{line: 166, col: 23, offset: 4835},
									label: "code",
									expr: &charClassMatcher{
										pos:        position{line: 166, col: 28, offset: 4840},
										val:        "[bdDfnrsStvwW]",
										chars:      []rune{'b', 'd', 'D', 'f', 'n', 'r', 's', 'S', 't', 'v', 'w', 'W'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 168, col: 5, offset: 4922},
						run: (*parser).callonCharsetEscape7,
						expr: &seqExpr{
							pos: position{line: 168, col: 5, offset: 4922},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 168, col: 5, offset: 4922},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 168, col: 10, offset: 4927},
									val:        "x",
									ignoreCase: false,
									want:       "\"x\"",
								},
								&charClassMatcher{
									pos:        position{line: 168, col: 14, offset: 4931},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 168, col: 26, offset: 4943},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 170, col: 5, offset: 5049},
						run: (*parser).callonCharsetEscape13,
						expr: &seqExpr{
							pos: position{line: 170, col: 5, offset: 5049},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 170, col: 5, offset: 5049},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 170, col: 10, offset: 5054},
									val:        "u",
									ignoreCase: false,
									want:       "\"u\"",
								},
								&litMatcher{
									pos:        position{line: 170, col: 14, offset: 5058},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&oneOrMoreExpr{
									pos: position{line: 170, col: 18, offset: 5062},
									expr: &charClassMatcher{
										pos:        position{line: 170, col: 18, offset: 5062},
										val:        "[0-9a-fA-F]",
										ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&litMatcher{
									pos:        position{line: 170, col: 31, offset: 5075},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 173, col: 5, offset: 5251},
						run: (*parser).callonCharsetEscape21,
						expr: &seqExpr{
							pos: position{line: 173, col: 5, offset: 5251},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 173, col: 5, offset: 5251},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 173, col: 10, offset: 5256},
									val:        "u",
									ignoreCase: false,
									want:       "\"u\"",
								},
								&charClassMatcher{
									pos:        position{line: 173, col: 14, offset: 5260},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 173, col: 26, offset: 5272},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 173, col: 38, offset: 5284},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 173, col: 50, offset: 5296},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 175, col: 5, offset: 5406},
						run: (*parser).callonCharsetEscape29,
						expr: &seqExpr{
							pos: position{line: 175, col: 5, offset: 5406},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 175, col: 5, offset: 5406},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 175, col: 10, offset: 5411},
									val:        "0",
									ignoreCase: false,
									want:       "\"0\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 175, col: 14, offset: 5415},
									expr: &charClassMatcher{
										pos:        position{line: 175, col: 14, offset: 5415},
										val:        "[0-7]",
										ranges:     []rune{'0', '7'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 177, col: 5, offset: 5518},
						run: (*parser).callonCharsetEscape35,
						expr: &seqExpr{
							pos: position{line: 177, col: 5, offset: 5518},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 177, col: 5, offset: 5518},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 177, col: 10, offset: 5523},
									val:        "c",
									ignoreCase: false,
									want:       "\"c\"",
								},
								&charClassMatcher{
									pos:        position{line: 177, col: 14, offset: 5527},
									val:        "[a-zA-Z]",
									ranges:     []rune{'a', 'z', 'A', 'Z'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CharsetLiteral",
			pos:  position{line: 182, col: 1, offset: 5694},
			expr: &choiceExpr{
				pos: position{line: 182, col: 19, offset: 5712},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 182, col: 19, offset: 5712},
						run: (*parser).callonCharsetLiteral2,
						expr: &charClassMatcher{
							pos:        position{line: 182, col: 19, offset: 5712},
							val:        "[^\\]\\\\]",
							chars:      []rune{']', '\\'},
							ignoreCase: false,
							inverted:   true,
						},
					},
					&actionExpr{
						pos: position{line: 184, col: 5, offset: 5780},
						run: (*parser).callonCharsetLiteral4,
						expr: &seqExpr{
							pos: position{line: 184, col: 5, offset: 5780},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 184, col: 5, offset: 5780},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&labeledExpr{
									pos:   position{line: 184, col: 10, offset: 5785},
									label: "char",
									expr: &anyMatcher{
										line: 184, col: 15, offset: 5790,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Terminal",
			pos:  position{line: 189, col: 1, offset: 5911},
			expr: &choiceExpr{
				pos: position{line: 189, col: 13, offset: 5923},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 189, col: 13, offset: 5923},
						name: "AnyChar",
					},
					&ruleRefExpr{
						pos:  position{line: 189, col: 23, offset: 5933},
						name: "Escape",
					},
					&ruleRefExpr{
						pos:  position{line: 189, col: 32, offset: 5942},
						name: "Literal",
					},
				},
			},
		},
		{
			name: "AnyChar",
			pos:  position{line: 192, col: 1, offset: 5983},
			expr: &actionExpr{
				pos: position{line: 192, col: 12, offset: 5994},
				run: (*parser).callonAnyChar1,
				expr: &litMatcher{
					pos:        position{line: 192, col: 12, offset: 5994},
					val:        ".",
					ignoreCase: false,
					want:       "\".\"",
				},
			},
		},
		{
			name: "Escape",
			pos:  position{line: 197, col: 1, offset: 6063},
			expr: &choiceExpr{
				pos: position{line: 197, col: 11, offset: 6073},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 197, col: 11, offset: 6073},
						run: (*parser).callonEscape2,
						expr: &seqExpr{
							pos: position{line: 197, col: 11, offset: 6073},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 197, col: 11, offset: 6073},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&labeledExpr{
									pos:   position{line: 197, col: 16, offset: 6078},
									label: "code",
									expr: &charClassMatcher{
										pos:        position{line: 197, col: 21, offset: 6083},
										val:        "[bBdDfnrsStvwW]",
										chars:      []rune{'b', 'B', 'd', 'D', 'f', 'n', 'r', 's', 'S', 't', 'v', 'w', 'W'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 199, col: 5, offset: 6166},
						run: (*parser).callonEscape7,
						expr: &seqExpr{
							pos: position{line: 199, col: 5, offset: 6166},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 199, col: 5, offset: 6166},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 199, col: 10, offset: 6171},
									val:        "p",
									ignoreCase: false,
									want:       "\"p\"",
								},
								&litMatcher{
									pos:        position{line: 199, col: 14, offset: 6175},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&labeledExpr{
									pos:   position{line: 199, col: 18, offset: 6179},
									label: "prop",
									expr: &ruleRefExpr{
										pos:  position{line: 199, col: 23, offset: 6184},
										name: "UnicodePropertyValue",
									},
								},
								&litMatcher{
									pos:        position{line: 199, col: 44, offset: 6205},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 202, col: 5, offset: 6334},
						run: (*parser).callonEscape15,
						expr: &seqExpr{
							pos: position{line: 202, col: 5, offset: 6334},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 202, col: 5, offset: 6334},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 202, col: 10, offset: 6339},
									val:        "P",
									ignoreCase: false,
									want:       "\"P\"",
								},
								&litMatcher{
									pos:        position{line: 202, col: 14, offset: 6343},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&labeledExpr{
									pos:   position{line: 202, col: 18, offset: 6347},
									label: "prop",
									expr: &ruleRefExpr{
										pos:  position{line: 202, col: 23, offset: 6352},
										name: "UnicodePropertyValue",
									},
								},
								&litMatcher{
									pos:        position{line: 202, col: 44, offset: 6373},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 205, col: 5, offset: 6509},
						run: (*parser).callonEscape23,
						expr: &seqExpr{
							pos: position{line: 205, col: 5, offset: 6509},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 205, col: 5, offset: 6509},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 205, col: 10, offset: 6514},
									val:        "k",
									ignoreCase: false,
									want:       "\"k\"",
								},
								&litMatcher{
									pos:        position{line: 205, col: 14, offset: 6518},
									val:        "<",
									ignoreCase: false,
									want:       "\"<\"",
								},
								&labeledExpr{
									pos:   position{line: 205, col: 18, offset: 6522},
									label: "name",
									expr: &ruleRefExpr{
										pos:  position{line: 205, col: 23, offset: 6527},
										name: "GroupName",
									},
								},
								&litMatcher{
									pos:        position{line: 205, col: 33, offset: 6537},
									val:        ">",
									ignoreCase: false,
									want:       "\">\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 208, col: 5, offset: 6635},
						run: (*parser).callonEscape31,
						expr: &seqExpr{
							pos: position{line: 208, col: 5, offset: 6635},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 208, col: 5, offset: 6635},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&labeledExpr{
									pos:   position{line: 208, col: 10, offset: 6640},
									label: "code",
									expr: &charClassMatcher{
										pos:        position{line: 208, col: 15, offset: 6645},
										val:        "[1-9]",
										ranges:     []rune{'1', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 211, col: 5, offset: 6740},
						run: (*parser).callonEscape36,
						expr: &seqExpr{
							pos: position{line: 211, col: 5, offset: 6740},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 211, col: 5, offset: 6740},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 211, col: 10, offset: 6745},
									val:        "x",
									ignoreCase: false,
									want:       "\"x\"",
								},
								&charClassMatcher{
									pos:        position{line: 211, col: 14, offset: 6749},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 211, col: 26, offset: 6761},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 213, col: 5, offset: 6867},
						run: (*parser).callonEscape42,
						expr: &seqExpr{
							pos: position{line: 213, col: 5, offset: 6867},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 213, col: 5, offset: 6867},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 213, col: 10, offset: 6872},
									val:        "u",
									ignoreCase: false,
									want:       "\"u\"",
								},
								&litMatcher{
									pos:        position{line: 213, col: 14, offset: 6876},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&oneOrMoreExpr{
									pos: position{line: 213, col: 18, offset: 6880},
									expr: &charClassMatcher{
										pos:        position{line: 213, col: 18, offset: 6880},
										val:        "[0-9a-fA-F]",
										ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&litMatcher{
									pos:        position{line: 213, col: 31, offset: 6893},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 216, col: 5, offset: 7069},
						run: (*parser).callonEscape50,
						expr: &seqExpr{
							pos: position{line: 216, col: 5, offset: 7069},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 216, col: 5, offset: 7069},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 216, col: 10, offset: 7074},
									val:        "u",
									ignoreCase: false,
									want:       "\"u\"",
								},
								&charClassMatcher{
									pos:        position{line: 216, col: 14, offset: 7078},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 216, col: 26, offset: 7090},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 216, col: 38, offset: 7102},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
								&charClassMatcher{
									pos:        position{line: 216, col: 50, offset: 7114},
									val:        "[0-9a-fA-F]",
									ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 218, col: 5, offset: 7224},
						run: (*parser).callonEscape58,
						expr: &seqExpr{
							pos: position{line: 218, col: 5, offset: 7224},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 218, col: 5, offset: 7224},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 218, col: 10, offset: 7229},
									val:        "0",
									ignoreCase: false,
									want:       "\"0\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 218, col: 14, offset: 7233},
									expr: &charClassMatcher{
										pos:        position{line: 218, col: 14, offset: 7233},
										val:        "[0-7]",
										ranges:     []rune{'0', '7'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 220, col: 5, offset: 7336},
						run: (*parser).callonEscape64,
						expr: &seqExpr{
							pos: position{line: 220, col: 5, offset: 7336},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 220, col: 5, offset: 7336},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 220, col: 10, offset: 7341},
									val:        "c",
									ignoreCase: false,
									want:       "\"c\"",
								},
								&charClassMatcher{
									pos:        position{line: 220, col: 14, offset: 7345},
									val:        "[a-zA-Z]",
									ranges:     []rune{'a', 'z', 'A', 'Z'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "UnicodePropertyValue",
			pos:  position{line: 225, col: 1, offset: 7525},
			expr: &actionExpr{
				pos: position{line: 225, col: 25, offset: 7549},
				run: (*parser).callonUnicodePropertyValue1,
				expr: &oneOrMoreExpr{
					pos: position{line: 225, col: 25, offset: 7549},
					expr: &charClassMatcher{
						pos:        position{line: 225, col: 25, offset: 7549},
						val:        "[a-zA-Z0-9_=]",
						chars:      []rune{'_', '='},
						ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Literal",
			pos:  position{line: 230, col: 1, offset: 7652},
			expr: &choiceExpr{
				pos: position{line: 230, col: 12, offset: 7663},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 230, col: 12, offset: 7663},
						run: (*parser).callonLiteral2,
						expr: &oneOrMoreExpr{
							pos: position{line: 230, col: 12, offset: 7663},
							expr: &ruleRefExpr{
								pos:  position{line: 230, col: 12, offset: 7663},
								name: "LiteralChars",
							},
						},
					},
					&actionExpr{
						pos: position{line: 232, col: 5, offset: 7730},
						run: (*parser).callonLiteral5,
						expr: &seqExpr{
							pos: position{line: 232, col: 5, offset: 7730},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 232, col: 5, offset: 7730},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&labeledExpr{
									pos:   position{line: 232, col: 10, offset: 7735},
									label: "char",
									expr: &anyMatcher{
										line: 232, col: 15, offset: 7740,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LiteralChars",
			pos:  position{line: 239, col: 1, offset: 7960},
			expr: &charClassMatcher{
				pos:        position{line: 239, col: 17, offset: 7976},
				val:        "[a-zA-Z0-9_ !@#%&:;\"'<>,`~=-]",
				chars:      []rune{'_', ' ', '!', '@', '#', '%', '&', ':', ';', '"', '\'', '<', '>', ',', '`', '~', '=', '-'},
				ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Repeat",
			pos:  position{line: 242, col: 1, offset: 8030},
			expr: &actionExpr{
				pos: position{line: 242, col: 11, offset: 8040},
				run: (*parser).callonRepeat1,
				expr: &seqExpr{
					pos: position{line: 242, col: 11, offset: 8040},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 242, col: 11, offset: 8040},
							label: "spec",
							expr: &ruleRefExpr{
								pos:  position{line: 242, col: 16, offset: 8045},
								name: "RepeatSpec",
							},
						},
						&labeledExpr{
							pos:   position{line: 242, col: 27, offset: 8056},
							label: "greedy",
							expr: &zeroOrOneExpr{
								pos: position{line: 242, col: 34, offset: 8063},
								expr: &litMatcher{
									pos:        position{line: 242, col: 34, offset: 8063},
									val:        "?",
									ignoreCase: false,
									want:       "\"?\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "RepeatSpec",
			pos:  position{line: 249, col: 1, offset: 8181},
			expr: &choiceExpr{
				pos: position{line: 249, col: 15, offset: 8195},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 249, col: 15, offset: 8195},
						run: (*parser).callonRepeatSpec2,
						expr: &litMatcher{
							pos:        position{line: 249, col: 15, offset: 8195},
							val:        "*",
							ignoreCase: false,
							want:       "\"*\"",
						},
					},
					&actionExpr{
						pos: position{line: 251, col: 5, offset: 8260},
						run: (*parser).callonRepeatSpec4,
						expr: &litMatcher{
							pos:        position{line: 251, col: 5, offset: 8260},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
					},
					&actionExpr{
						pos: position{line: 253, col: 5, offset: 8325},
						run: (*parser).callonRepeatSpec6,
						expr: &litMatcher{
							pos:        position{line: 253, col: 5, offset: 8325},
							val:        "?",
							ignoreCase: false,
							want:       "\"?\"",
						},
					},
					&actionExpr{
						pos: position{line: 255, col: 5, offset: 8389},
						run: (*parser).callonRepeatSpec8,
						expr: &seqExpr{
							pos: position{line: 255, col: 5, offset: 8389},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 255, col: 5, offset: 8389},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&labeledExpr{
									pos:   position{line: 255, col: 9, offset: 8393},
									label: "min",
									expr: &oneOrMoreExpr{
										pos: position{line: 255, col: 13, offset: 8397},
										expr: &charClassMatcher{
											pos:        position{line: 255, col: 13, offset: 8397},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
								&litMatcher{
									pos:        position{line: 255, col: 20, offset: 8404},
									val:        ",",
									ignoreCase: false,
									want:       "\",\"",
								},
								&labeledExpr{
									pos:   position{line: 255, col: 24, offset: 8408},
									label: "max",
									expr: &oneOrMoreExpr{
										pos: position{line: 255, col: 28, offset: 8412},
										expr: &charClassMatcher{
											pos:        position{line: 255, col: 28, offset: 8412},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
								&litMatcher{
									pos:        position{line: 255, col: 35, offset: 8419},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 259, col: 5, offset: 8549},
						run: (*parser).callonRepeatSpec19,
						expr: &seqExpr{
							pos: position{line: 259, col: 5, offset: 8549},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 259, col: 5, offset: 8549},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&labeledExpr{
									pos:   position{line: 259, col: 9, offset: 8553},
									label: "min",
									expr: &oneOrMoreExpr{
										pos: position{line: 259, col: 13, offset: 8557},
										expr: &charClassMatcher{
											pos:        position{line: 259, col: 13, offset: 8557},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
								&litMatcher{
									pos:        position{line: 259, col: 20, offset: 8564},
									val:        ",",
									ignoreCase: false,
									want:       "\",\"",
								},
								&litMatcher{
									pos:        position{line: 259, col: 24, offset: 8568},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 262, col: 5, offset: 8666},
						run: (*parser).callonRepeatSpec27,
						expr: &seqExpr{
							pos: position{line: 262, col: 5, offset: 8666},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 262, col: 5, offset: 8666},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&labeledExpr{
									pos:   position{line: 262, col: 9, offset: 8670},
									label: "exact",
									expr: &oneOrMoreExpr{
										pos: position{line: 262, col: 15, offset: 8676},
										expr: &charClassMatcher{
											pos:        position{line: 262, col: 15, offset: 8676},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
								&litMatcher{
									pos:        position{line: 262, col: 22, offset: 8683},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 267, col: 1, offset: 8777},
			expr: &notExpr{
				pos: position{line: 267, col: 8, offset: 8784},
				expr: &anyMatcher{
					line: 267, col: 9, offset: 8785,
				},
			},
		},
	},
}

func (c *current) onSlashDelimited1(regexp, flags any) (any, error) {
	r := regexp.(*Regexp)
	if flags != nil {
		r.Flags = flags.(string)
	}
	return r, nil
}

func (p *parser) callonSlashDelimited1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSlashDelimited1(stack["regexp"], stack["flags"])
}

func (c *current) onPlainRegexp1(regexp any) (any, error) {
	return regexp.(*Regexp), nil
}

func (p *parser) callonPlainRegexp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPlainRegexp1(stack["regexp"])
}

func (c *current) onFlags1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonFlags1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFlags1()
}

func (c *current) onRegexp1(first, rest any) (any, error) {
	matches := []*Match{first.(*Match)}
	if rest != nil {
		for _, r := range rest.([]any) {
			pair := r.([]any)
			matches = append(matches, pair[1].(*Match))
		}
	}
	return &Regexp{Matches: matches}, nil
}

func (p *parser) callonRegexp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRegexp1(stack["first"], stack["rest"])
}

func (c *current) onMatch1(frags any) (any, error) {
	fragments := []*MatchFragment{}
	if frags != nil {
		for _, f := range frags.([]any) {
			fragments = append(fragments, f.(*MatchFragment))
		}
	}
	return &Match{Fragments: fragments}, nil
}

func (p *parser) callonMatch1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatch1(stack["frags"])
}

func (c *current) onMatchFragment1(content, repeat any) (any, error) {
	mf := &MatchFragment{Content: content.(Node)}
	if repeat != nil {
		mf.Repeat = repeat.(*Repeat)
	}
	return mf, nil
}

func (p *parser) callonMatchFragment1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchFragment1(stack["content"], stack["repeat"])
}

func (c *current) onAnchor1() (any, error) {
	anchorType := "start"
	if string(c.text) == "$" {
		anchorType = "end"
	}
	return &Anchor{AnchorType: anchorType}, nil
}

func (p *parser) callonAnchor1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnchor1()
}

func (c *current) onSubexp1(groupType, regexp any) (any, error) {
	s := &Subexp{Regexp: regexp.(*Regexp)}
	if groupType != nil {
		switch gt := groupType.(type) {
		case string:
			// Simple group type (non_capture, lookahead, lookbehind)
			s.GroupType = gt
			s.Number = 0
		case map[string]any:
			// Named capture group
			s.GroupType = gt["type"].(string)
			s.Name = gt["name"].(string)
			s.Number = parserState(c).NextGroupNumber()
		}
	} else {
		s.GroupType = "capture"
		s.Number = parserState(c).NextGroupNumber()
	}
	return s, nil
}

func (p *parser) callonSubexp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSubexp1(stack["groupType"], stack["regexp"])
}

func (c *current) onGroupType2() (any, error) {
	return "non_capture", nil
}

func (p *parser) callonGroupType2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGroupType2()
}

func (c *current) onGroupType4() (any, error) {
	return "positive_lookahead", nil
}

func (p *parser) callonGroupType4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGroupType4()
}

func (c *current) onGroupType6() (any, error) {
	return "negative_lookahead", nil
}

func (p *parser) callonGroupType6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGroupType6()
}

func (c *current) onGroupType8() (any, error) {
	return "positive_lookbehind", nil
}

func (p *parser) callonGroupType8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGroupType8()
}

func (c *current) onGroupType10() (any, error) {
	return "negative_lookbehind", nil
}

func (p *parser) callonGroupType10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGroupType10()
}

func (c *current) onGroupType12(name any) (any, error) {
	return map[string]any{"type": "named_capture", "name": name.(string)}, nil

}

func (p *parser) callonGroupType12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGroupType12(stack["name"])
}

func (c *current) onGroupName1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonGroupName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGroupName1()
}

func (c *current) onCharset1(inverted, items any) (any, error) {
	charset := &Charset{
		Inverted: inverted != nil,
		Items:    []CharsetItem{},
	}
	if items != nil {
		for _, item := range items.([]any) {
			charset.Items = append(charset.Items, item.(CharsetItem))
		}
	}
	return charset, nil
}

func (p *parser) callonCharset1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharset1(stack["inverted"], stack["items"])
}

func (c *current) onCharsetRange1(first, last any) (any, error) {
	return &CharsetRange{
		First: first.(string),
		Last:  last.(string),
	}, nil
}

func (p *parser) callonCharsetRange1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetRange1(stack["first"], stack["last"])
}

func (c *current) onCharsetRangeEscape2() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCharsetRangeEscape2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetRangeEscape2()
}

func (c *current) onCharsetRangeEscape6() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCharsetRangeEscape6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetRangeEscape6()
}

func (c *current) onCharsetRangeEscape12() (any, error) {
	// Braced Unicode escape for range bound
	return string(c.text), nil
}

func (p *parser) callonCharsetRangeEscape12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetRangeEscape12()
}

func (c *current) onCharsetRangeEscape20() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCharsetRangeEscape20() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetRangeEscape20()
}

func (c *current) onCharsetRangeEscape28() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCharsetRangeEscape28() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetRangeEscape28()
}

func (c *current) onCharsetRangeEscape34() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCharsetRangeEscape34() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetRangeEscape34()
}

func (c *current) onCharsetRangeLiteral2() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCharsetRangeLiteral2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetRangeLiteral2()
}

func (c *current) onCharsetRangeLiteral4() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCharsetRangeLiteral4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetRangeLiteral4()
}

func (c *current) onCharsetEscape2(code any) (any, error) {
	return makeEscape(string([]byte{code.([]byte)[0]})), nil
}

func (p *parser) callonCharsetEscape2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetEscape2(stack["code"])
}

func (c *current) onCharsetEscape7() (any, error) {
	return &Escape{EscapeType: "hex", Code: string(c.text), Value: string(c.text)}, nil
}

func (p *parser) callonCharsetEscape7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetEscape7()
}

func (c *current) onCharsetEscape13() (any, error) {
	// Braced Unicode escape \u{HHHHHH} for code points beyond BMP
	return &Escape{EscapeType: "unicode_braced", Code: string(c.text), Value: string(c.text)}, nil
}

func (p *parser) callonCharsetEscape13() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetEscape13()
}

func (c *current) onCharsetEscape21() (any, error) {
	return &Escape{EscapeType: "unicode", Code: string(c.text), Value: string(c.text)}, nil
}

func (p *parser) callonCharsetEscape21() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetEscape21()
}

func (c *current) onCharsetEscape29() (any, error) {
	return &Escape{EscapeType: "octal", Code: string(c.text), Value: string(c.text)}, nil
}

func (p *parser) callonCharsetEscape29() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetEscape29()
}

func (c *current) onCharsetEscape35() (any, error) {
	return &Escape{EscapeType: "control", Code: string(c.text), Value: string(c.text)}, nil
}

func (p *parser) callonCharsetEscape35() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetEscape35()
}

func (c *current) onCharsetLiteral2() (any, error) {
	return &CharsetLiteral{Text: string(c.text)}, nil
}

func (p *parser) callonCharsetLiteral2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetLiteral2()
}

func (c *current) onCharsetLiteral4(char any) (any, error) {
	return &CharsetLiteral{Text: string(char.([]byte))}, nil
}

func (p *parser) callonCharsetLiteral4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetLiteral4(stack["char"])
}

func (c *current) onAnyChar1() (any, error) {
	return &AnyCharacter{}, nil
}

func (p *parser) callonAnyChar1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnyChar1()
}

func (c *current) onEscape2(code any) (any, error) {
	return makeEscape(string([]byte{code.([]byte)[0]})), nil
}

func (p *parser) callonEscape2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape2(stack["code"])
}

func (c *current) onEscape7(prop any) (any, error) {
	// Unicode property escape \p{...}
	return &UnicodePropertyEscape{Property: prop.(string), Negated: false}, nil
}

func (p *parser) callonEscape7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape7(stack["prop"])
}

func (c *current) onEscape15(prop any) (any, error) {
	// Negated Unicode property escape \P{...}
	return &UnicodePropertyEscape{Property: prop.(string), Negated: true}, nil
}

func (p *parser) callonEscape15() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape15(stack["prop"])
}

func (c *current) onEscape23(name any) (any, error) {
	// Named backreference \k<name>
	return &BackReference{Name: name.(string)}, nil
}

func (p *parser) callonEscape23() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape23(stack["name"])
}

func (c *current) onEscape31(code any) (any, error) {
	num := int(code.([]byte)[0] - '0')
	return &BackReference{Number: num}, nil
}

func (p *parser) callonEscape31() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape31(stack["code"])
}

func (c *current) onEscape36() (any, error) {
	return &Escape{EscapeType: "hex", Code: string(c.text), Value: string(c.text)}, nil
}

func (p *parser) callonEscape36() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape36()
}

func (c *current) onEscape42() (any, error) {
	// Braced Unicode escape \u{HHHHHH} for code points beyond BMP
	return &Escape{EscapeType: "unicode_braced", Code: string(c.text), Value: string(c.text)}, nil
}

func (p *parser) callonEscape42() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape42()
}

func (c *current) onEscape50() (any, error) {
	return &Escape{EscapeType: "unicode", Code: string(c.text), Value: string(c.text)}, nil
}

func (p *parser) callonEscape50() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape50()
}

func (c *current) onEscape58() (any, error) {
	return &Escape{EscapeType: "octal", Code: string(c.text), Value: string(c.text)}, nil
}

func (p *parser) callonEscape58() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape58()
}

func (c *current) onEscape64() (any, error) {
	return &Escape{EscapeType: "control", Code: string(c.text), Value: string(c.text)}, nil
}

func (p *parser) callonEscape64() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape64()
}

func (c *current) onUnicodePropertyValue1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUnicodePropertyValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnicodePropertyValue1()
}

func (c *current) onLiteral2() (any, error) {
	return &Literal{Text: string(c.text)}, nil
}

func (p *parser) callonLiteral2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLiteral2()
}

func (c *current) onLiteral5(char any) (any, error) {
	// Escaped character becomes literal
	return &Literal{Text: string(char.([]byte))}, nil
}

func (p *parser) callonLiteral5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLiteral5(stack["char"])
}

func (c *current) onRepeat1(spec, greedy any) (any, error) {
	r := spec.(*Repeat)
	r.Greedy = greedy == nil
	return r, nil
}

func (p *parser) callonRepeat1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeat1(stack["spec"], stack["greedy"])
}

func (c *current) onRepeatSpec2() (any, error) {
	return &Repeat{Min: 0, Max: -1, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec2()
}

func (c *current) onRepeatSpec4() (any, error) {
	return &Repeat{Min: 1, Max: -1, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec4()
}

func (c *current) onRepeatSpec6() (any, error) {
	return &Repeat{Min: 0, Max: 1, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec6()
}

func (c *current) onRepeatSpec8(min, max any) (any, error) {
	minVal := parseInt(min)
	maxVal := parseInt(max)
	return &Repeat{Min: minVal, Max: maxVal, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec8(stack["min"], stack["max"])
}

func (c *current) onRepeatSpec19(min any) (any, error) {
	minVal := parseInt(min)
	return &Repeat{Min: minVal, Max: -1, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec19() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec19(stack["min"])
}

func (c *current) onRepeatSpec27(exact any) (any, error) {
	val := parseInt(exact)
	return &Repeat{Min: val, Max: val, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec27() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec27(stack["exact"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
