// Code generated by pigeon; DO NOT EDIT.

package gnugrep_ere

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/0x4d5352/regolith/internal/ast"
)

// parserState returns the parser state from the global state map
func parserState(c *current) *ast.ParserState {
	return c.globalStore["state"].(*ast.ParserState)
}

// silence unused import error
var _ = fmt.Errorf

var g = &grammar{
	rules: []*rule{
		{
			name: "Root",
			pos:  position{line: 20, col: 1, offset: 391},
			expr: &actionExpr{
				pos: position{line: 20, col: 9, offset: 399},
				run: (*parser).callonRoot1,
				expr: &seqExpr{
					pos: position{line: 20, col: 9, offset: 399},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 20, col: 9, offset: 399},
							label: "regexp",
							expr: &ruleRefExpr{
								pos:  position{line: 20, col: 16, offset: 406},
								name: "Regexp",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 20, col: 23, offset: 413},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Regexp",
			pos:  position{line: 25, col: 1, offset: 510},
			expr: &actionExpr{
				pos: position{line: 25, col: 11, offset: 520},
				run: (*parser).callonRegexp1,
				expr: &seqExpr{
					pos: position{line: 25, col: 11, offset: 520},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 25, col: 11, offset: 520},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 25, col: 17, offset: 526},
								name: "Match",
							},
						},
						&labeledExpr{
							pos:   position{line: 25, col: 23, offset: 532},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 25, col: 28, offset: 537},
								expr: &seqExpr{
									pos: position{line: 25, col: 30, offset: 539},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 25, col: 30, offset: 539},
											val:        "|",
											ignoreCase: false,
											want:       "\"|\"",
										},
										&ruleRefExpr{
											pos:  position{line: 25, col: 34, offset: 543},
											name: "Match",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Match",
			pos:  position{line: 37, col: 1, offset: 855},
			expr: &actionExpr{
				pos: position{line: 37, col: 10, offset: 864},
				run: (*parser).callonMatch1,
				expr: &labeledExpr{
					pos:   position{line: 37, col: 10, offset: 864},
					label: "frags",
					expr: &zeroOrMoreExpr{
						pos: position{line: 37, col: 16, offset: 870},
						expr: &ruleRefExpr{
							pos:  position{line: 37, col: 16, offset: 870},
							name: "MatchFragment",
						},
					},
				},
			},
		},
		{
			name: "MatchFragment",
			pos:  position{line: 48, col: 1, offset: 1174},
			expr: &actionExpr{
				pos: position{line: 48, col: 18, offset: 1191},
				run: (*parser).callonMatchFragment1,
				expr: &seqExpr{
					pos: position{line: 48, col: 18, offset: 1191},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 48, col: 18, offset: 1191},
							label: "content",
							expr: &ruleRefExpr{
								pos:  position{line: 48, col: 26, offset: 1199},
								name: "Content",
							},
						},
						&labeledExpr{
							pos:   position{line: 48, col: 34, offset: 1207},
							label: "repeat",
							expr: &zeroOrOneExpr{
								pos: position{line: 48, col: 41, offset: 1214},
								expr: &ruleRefExpr{
									pos:  position{line: 48, col: 41, offset: 1214},
									name: "Repeat",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Content",
			pos:  position{line: 57, col: 1, offset: 1424},
			expr: &choiceExpr{
				pos: position{line: 57, col: 12, offset: 1435},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 57, col: 12, offset: 1435},
						name: "Anchor",
					},
					&ruleRefExpr{
						pos:  position{line: 57, col: 21, offset: 1444},
						name: "Subexp",
					},
					&ruleRefExpr{
						pos:  position{line: 57, col: 30, offset: 1453},
						name: "Charset",
					},
					&ruleRefExpr{
						pos:  position{line: 57, col: 40, offset: 1463},
						name: "BackReference",
					},
					&ruleRefExpr{
						pos:  position{line: 57, col: 56, offset: 1479},
						name: "Terminal",
					},
				},
			},
		},
		{
			name: "Anchor",
			pos:  position{line: 60, col: 1, offset: 1518},
			expr: &actionExpr{
				pos: position{line: 60, col: 11, offset: 1528},
				run: (*parser).callonAnchor1,
				expr: &choiceExpr{
					pos: position{line: 60, col: 13, offset: 1530},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 60, col: 13, offset: 1530},
							val:        "^",
							ignoreCase: false,
							want:       "\"^\"",
						},
						&litMatcher{
							pos:        position{line: 60, col: 19, offset: 1536},
							val:        "$",
							ignoreCase: false,
							want:       "\"$\"",
						},
					},
				},
			},
		},
		{
			name: "Subexp",
			pos:  position{line: 69, col: 1, offset: 1756},
			expr: &actionExpr{
				pos: position{line: 69, col: 11, offset: 1766},
				run: (*parser).callonSubexp1,
				expr: &seqExpr{
					pos: position{line: 69, col: 11, offset: 1766},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 69, col: 11, offset: 1766},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&labeledExpr{
							pos:   position{line: 69, col: 15, offset: 1770},
							label: "regexp",
							expr: &ruleRefExpr{
								pos:  position{line: 69, col: 22, offset: 1777},
								name: "Regexp",
							},
						},
						&litMatcher{
							pos:        position{line: 69, col: 29, offset: 1784},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "BackReference",
			pos:  position{line: 79, col: 1, offset: 2018},
			expr: &actionExpr{
				pos: position{line: 79, col: 18, offset: 2035},
				run: (*parser).callonBackReference1,
				expr: &seqExpr{
					pos: position{line: 79, col: 18, offset: 2035},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 79, col: 18, offset: 2035},
							val:        "\\",
							ignoreCase: false,
							want:       "\"\\\\\"",
						},
						&labeledExpr{
							pos:   position{line: 79, col: 23, offset: 2040},
							label: "num",
							expr: &charClassMatcher{
								pos:        position{line: 79, col: 27, offset: 2044},
								val:        "[1-9]",
								ranges:     []rune{'1', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Charset",
			pos:  position{line: 86, col: 1, offset: 2226},
			expr: &actionExpr{
				pos: position{line: 86, col: 12, offset: 2237},
				run: (*parser).callonCharset1,
				expr: &seqExpr{
					pos: position{line: 86, col: 12, offset: 2237},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 86, col: 12, offset: 2237},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&labeledExpr{
							pos:   position{line: 86, col: 16, offset: 2241},
							label: "inverted",
							expr: &zeroOrOneExpr{
								pos: position{line: 86, col: 25, offset: 2250},
								expr: &litMatcher{
									pos:        position{line: 86, col: 25, offset: 2250},
									val:        "^",
									ignoreCase: false,
									want:       "\"^\"",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 86, col: 30, offset: 2255},
							label: "items",
							expr: &zeroOrMoreExpr{
								pos: position{line: 86, col: 36, offset: 2261},
								expr: &ruleRefExpr{
									pos:  position{line: 86, col: 36, offset: 2261},
									name: "CharsetItem",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 86, col: 49, offset: 2274},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "CharsetItem",
			pos:  position{line: 101, col: 1, offset: 2699},
			expr: &choiceExpr{
				pos: position{line: 101, col: 16, offset: 2714},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 101, col: 16, offset: 2714},
						name: "POSIXClass",
					},
					&ruleRefExpr{
						pos:  position{line: 101, col: 29, offset: 2727},
						name: "CharsetRange",
					},
					&ruleRefExpr{
						pos:  position{line: 101, col: 44, offset: 2742},
						name: "CharsetEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 101, col: 60, offset: 2758},
						name: "CharsetLiteral",
					},
				},
			},
		},
		{
			name: "POSIXClass",
			pos:  position{line: 104, col: 1, offset: 2831},
			expr: &choiceExpr{
				pos: position{line: 104, col: 15, offset: 2845},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 104, col: 15, offset: 2845},
						run: (*parser).callonPOSIXClass2,
						expr: &seqExpr{
							pos: position{line: 104, col: 15, offset: 2845},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 104, col: 15, offset: 2845},
									val:        "[:",
									ignoreCase: false,
									want:       "\"[:\"",
								},
								&labeledExpr{
									pos:   position{line: 104, col: 20, offset: 2850},
									label: "name",
									expr: &ruleRefExpr{
										pos:  position{line: 104, col: 25, offset: 2855},
										name: "POSIXClassName",
									},
								},
								&litMatcher{
									pos:        position{line: 104, col: 40, offset: 2870},
									val:        ":]",
									ignoreCase: false,
									want:       "\":]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 106, col: 5, offset: 2950},
						run: (*parser).callonPOSIXClass8,
						expr: &seqExpr{
							pos: position{line: 106, col: 5, offset: 2950},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 106, col: 5, offset: 2950},
									val:        "[:^",
									ignoreCase: false,
									want:       "\"[:^\"",
								},
								&labeledExpr{
									pos:   position{line: 106, col: 11, offset: 2956},
									label: "name",
									expr: &ruleRefExpr{
										pos:  position{line: 106, col: 16, offset: 2961},
										name: "POSIXClassName",
									},
								},
								&litMatcher{
									pos:        position{line: 106, col: 31, offset: 2976},
									val:        ":]",
									ignoreCase: false,
									want:       "\":]\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "POSIXClassName",
			pos:  position{line: 112, col: 1, offset: 3166},
			expr: &choiceExpr{
				pos: position{line: 112, col: 19, offset: 3184},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 112, col: 19, offset: 3184},
						run: (*parser).callonPOSIXClassName2,
						expr: &litMatcher{
							pos:        position{line: 112, col: 19, offset: 3184},
							val:        "alnum",
							ignoreCase: false,
							want:       "\"alnum\"",
						},
					},
					&actionExpr{
						pos: position{line: 113, col: 17, offset: 3232},
						run: (*parser).callonPOSIXClassName4,
						expr: &litMatcher{
							pos:        position{line: 113, col: 17, offset: 3232},
							val:        "alpha",
							ignoreCase: false,
							want:       "\"alpha\"",
						},
					},
					&actionExpr{
						pos: position{line: 114, col: 17, offset: 3280},
						run: (*parser).callonPOSIXClassName6,
						expr: &litMatcher{
							pos:        position{line: 114, col: 17, offset: 3280},
							val:        "blank",
							ignoreCase: false,
							want:       "\"blank\"",
						},
					},
					&actionExpr{
						pos: position{line: 115, col: 17, offset: 3328},
						run: (*parser).callonPOSIXClassName8,
						expr: &litMatcher{
							pos:        position{line: 115, col: 17, offset: 3328},
							val:        "cntrl",
							ignoreCase: false,
							want:       "\"cntrl\"",
						},
					},
					&actionExpr{
						pos: position{line: 116, col: 17, offset: 3376},
						run: (*parser).callonPOSIXClassName10,
						expr: &litMatcher{
							pos:        position{line: 116, col: 17, offset: 3376},
							val:        "digit",
							ignoreCase: false,
							want:       "\"digit\"",
						},
					},
					&actionExpr{
						pos: position{line: 117, col: 17, offset: 3424},
						run: (*parser).callonPOSIXClassName12,
						expr: &litMatcher{
							pos:        position{line: 117, col: 17, offset: 3424},
							val:        "graph",
							ignoreCase: false,
							want:       "\"graph\"",
						},
					},
					&actionExpr{
						pos: position{line: 118, col: 17, offset: 3472},
						run: (*parser).callonPOSIXClassName14,
						expr: &litMatcher{
							pos:        position{line: 118, col: 17, offset: 3472},
							val:        "lower",
							ignoreCase: false,
							want:       "\"lower\"",
						},
					},
					&actionExpr{
						pos: position{line: 119, col: 17, offset: 3520},
						run: (*parser).callonPOSIXClassName16,
						expr: &litMatcher{
							pos:        position{line: 119, col: 17, offset: 3520},
							val:        "print",
							ignoreCase: false,
							want:       "\"print\"",
						},
					},
					&actionExpr{
						pos: position{line: 120, col: 17, offset: 3568},
						run: (*parser).callonPOSIXClassName18,
						expr: &litMatcher{
							pos:        position{line: 120, col: 17, offset: 3568},
							val:        "punct",
							ignoreCase: false,
							want:       "\"punct\"",
						},
					},
					&actionExpr{
						pos: position{line: 121, col: 17, offset: 3616},
						run: (*parser).callonPOSIXClassName20,
						expr: &litMatcher{
							pos:        position{line: 121, col: 17, offset: 3616},
							val:        "space",
							ignoreCase: false,
							want:       "\"space\"",
						},
					},
					&actionExpr{
						pos: position{line: 122, col: 17, offset: 3664},
						run: (*parser).callonPOSIXClassName22,
						expr: &litMatcher{
							pos:        position{line: 122, col: 17, offset: 3664},
							val:        "upper",
							ignoreCase: false,
							want:       "\"upper\"",
						},
					},
					&actionExpr{
						pos: position{line: 123, col: 17, offset: 3712},
						run: (*parser).callonPOSIXClassName24,
						expr: &litMatcher{
							pos:        position{line: 123, col: 17, offset: 3712},
							val:        "xdigit",
							ignoreCase: false,
							want:       "\"xdigit\"",
						},
					},
				},
			},
		},
		{
			name: "CharsetRange",
			pos:  position{line: 126, col: 1, offset: 3768},
			expr: &actionExpr{
				pos: position{line: 126, col: 17, offset: 3784},
				run: (*parser).callonCharsetRange1,
				expr: &seqExpr{
					pos: position{line: 126, col: 17, offset: 3784},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 126, col: 17, offset: 3784},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 126, col: 23, offset: 3790},
								name: "CharsetRangeBound",
							},
						},
						&litMatcher{
							pos:        position{line: 126, col: 41, offset: 3808},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
						&labeledExpr{
							pos:   position{line: 126, col: 45, offset: 3812},
							label: "last",
							expr: &ruleRefExpr{
								pos:  position{line: 126, col: 50, offset: 3817},
								name: "CharsetRangeBound",
							},
						},
					},
				},
			},
		},
		{
			name: "CharsetRangeBound",
			pos:  position{line: 134, col: 1, offset: 3993},
			expr: &choiceExpr{
				pos: position{line: 134, col: 22, offset: 4014},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 134, col: 22, offset: 4014},
						name: "CharsetRangeEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 134, col: 43, offset: 4035},
						name: "CharsetRangeLiteral",
					},
				},
			},
		},
		{
			name: "CharsetRangeEscape",
			pos:  position{line: 138, col: 1, offset: 4152},
			expr: &actionExpr{
				pos: position{line: 138, col: 23, offset: 4174},
				run: (*parser).callonCharsetRangeEscape1,
				expr: &seqExpr{
					pos: position{line: 138, col: 23, offset: 4174},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 138, col: 23, offset: 4174},
							val:        "\\",
							ignoreCase: false,
							want:       "\"\\\\\"",
						},
						&labeledExpr{
							pos:   position{line: 138, col: 28, offset: 4179},
							label: "char",
							expr: &ruleRefExpr{
								pos:  position{line: 138, col: 33, offset: 4184},
								name: "MetaChar",
							},
						},
					},
				},
			},
		},
		{
			name: "MetaChar",
			pos:  position{line: 143, col: 1, offset: 4295},
			expr: &choiceExpr{
				pos: position{line: 143, col: 13, offset: 4307},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 143, col: 13, offset: 4307},
						val:        ".",
						ignoreCase: false,
						want:       "\".\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 19, offset: 4313},
						val:        "[",
						ignoreCase: false,
						want:       "\"[\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 25, offset: 4319},
						val:        "]",
						ignoreCase: false,
						want:       "\"]\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 31, offset: 4325},
						val:        "\\",
						ignoreCase: false,
						want:       "\"\\\\\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 38, offset: 4332},
						val:        "^",
						ignoreCase: false,
						want:       "\"^\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 44, offset: 4338},
						val:        "$",
						ignoreCase: false,
						want:       "\"$\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 50, offset: 4344},
						val:        "*",
						ignoreCase: false,
						want:       "\"*\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 56, offset: 4350},
						val:        "+",
						ignoreCase: false,
						want:       "\"+\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 62, offset: 4356},
						val:        "?",
						ignoreCase: false,
						want:       "\"?\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 68, offset: 4362},
						val:        "{",
						ignoreCase: false,
						want:       "\"{\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 74, offset: 4368},
						val:        "}",
						ignoreCase: false,
						want:       "\"}\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 80, offset: 4374},
						val:        "(",
						ignoreCase: false,
						want:       "\"(\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 86, offset: 4380},
						val:        ")",
						ignoreCase: false,
						want:       "\")\"",
					},
					&litMatcher{
						pos:        position{line: 143, col: 92, offset: 4386},
						val:        "|",
						ignoreCase: false,
						want:       "\"|\"",
					},
				},
			},
		},
		{
			name: "CharsetRangeLiteral",
			pos:  position{line: 146, col: 1, offset: 4465},
			expr: &actionExpr{
				pos: position{line: 146, col: 24, offset: 4488},
				run: (*parser).callonCharsetRangeLiteral1,
				expr: &charClassMatcher{
					pos:        position{line: 146, col: 24, offset: 4488},
					val:        "[^-\\]\\\\]",
					chars:      []rune{'-', ']', '\\'},
					ignoreCase: false,
					inverted:   true,
				},
			},
		},
		{
			name: "CharsetEscape",
			pos:  position{line: 151, col: 1, offset: 4578},
			expr: &actionExpr{
				pos: position{line: 151, col: 18, offset: 4595},
				run: (*parser).callonCharsetEscape1,
				expr: &seqExpr{
					pos: position{line: 151, col: 18, offset: 4595},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 151, col: 18, offset: 4595},
							val:        "\\",
							ignoreCase: false,
							want:       "\"\\\\\"",
						},
						&labeledExpr{
							pos:   position{line: 151, col: 23, offset: 4600},
							label: "char",
							expr: &ruleRefExpr{
								pos:  position{line: 151, col: 28, offset: 4605},
								name: "MetaChar",
							},
						},
					},
				},
			},
		},
		{
			name: "CharsetLiteral",
			pos:  position{line: 156, col: 1, offset: 4732},
			expr: &choiceExpr{
				pos: position{line: 156, col: 19, offset: 4750},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 156, col: 19, offset: 4750},
						run: (*parser).callonCharsetLiteral2,
						expr: &charClassMatcher{
							pos:        position{line: 156, col: 19, offset: 4750},
							val:        "[^\\]\\\\]",
							chars:      []rune{']', '\\'},
							ignoreCase: false,
							inverted:   true,
						},
					},
					&actionExpr{
						pos: position{line: 158, col: 5, offset: 4822},
						run: (*parser).callonCharsetLiteral4,
						expr: &seqExpr{
							pos: position{line: 158, col: 5, offset: 4822},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 158, col: 5, offset: 4822},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&labeledExpr{
									pos:   position{line: 158, col: 10, offset: 4827},
									label: "char",
									expr: &anyMatcher{
										line: 158, col: 15, offset: 4832,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Terminal",
			pos:  position{line: 164, col: 1, offset: 5022},
			expr: &choiceExpr{
				pos: position{line: 164, col: 13, offset: 5034},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 164, col: 13, offset: 5034},
						name: "AnyChar",
					},
					&ruleRefExpr{
						pos:  position{line: 164, col: 23, offset: 5044},
						name: "Escape",
					},
					&ruleRefExpr{
						pos:  position{line: 164, col: 32, offset: 5053},
						name: "Literal",
					},
				},
			},
		},
		{
			name: "AnyChar",
			pos:  position{line: 167, col: 1, offset: 5094},
			expr: &actionExpr{
				pos: position{line: 167, col: 12, offset: 5105},
				run: (*parser).callonAnyChar1,
				expr: &litMatcher{
					pos:        position{line: 167, col: 12, offset: 5105},
					val:        ".",
					ignoreCase: false,
					want:       "\".\"",
				},
			},
		},
		{
			name: "Escape",
			pos:  position{line: 174, col: 1, offset: 5283},
			expr: &choiceExpr{
				pos: position{line: 174, col: 11, offset: 5293},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 174, col: 11, offset: 5293},
						run: (*parser).callonEscape2,
						expr: &seqExpr{
							pos: position{line: 174, col: 11, offset: 5293},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 174, col: 11, offset: 5293},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 174, col: 16, offset: 5298},
									val:        "<",
									ignoreCase: false,
									want:       "\"<\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 177, col: 5, offset: 5403},
						run: (*parser).callonEscape6,
						expr: &seqExpr{
							pos: position{line: 177, col: 5, offset: 5403},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 177, col: 5, offset: 5403},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 177, col: 10, offset: 5408},
									val:        ">",
									ignoreCase: false,
									want:       "\">\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 180, col: 5, offset: 5509},
						run: (*parser).callonEscape10,
						expr: &seqExpr{
							pos: position{line: 180, col: 5, offset: 5509},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 180, col: 5, offset: 5509},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 180, col: 10, offset: 5514},
									val:        "b",
									ignoreCase: false,
									want:       "\"b\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 183, col: 5, offset: 5618},
						run: (*parser).callonEscape14,
						expr: &seqExpr{
							pos: position{line: 183, col: 5, offset: 5618},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 183, col: 5, offset: 5618},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 183, col: 10, offset: 5623},
									val:        "B",
									ignoreCase: false,
									want:       "\"B\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 186, col: 5, offset: 5735},
						run: (*parser).callonEscape18,
						expr: &seqExpr{
							pos: position{line: 186, col: 5, offset: 5735},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 186, col: 5, offset: 5735},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 186, col: 10, offset: 5740},
									val:        "w",
									ignoreCase: false,
									want:       "\"w\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 189, col: 5, offset: 5899},
						run: (*parser).callonEscape22,
						expr: &seqExpr{
							pos: position{line: 189, col: 5, offset: 5899},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 189, col: 5, offset: 5899},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 189, col: 10, offset: 5904},
									val:        "W",
									ignoreCase: false,
									want:       "\"W\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 192, col: 5, offset: 6076},
						run: (*parser).callonEscape26,
						expr: &seqExpr{
							pos: position{line: 192, col: 5, offset: 6076},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 192, col: 5, offset: 6076},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 192, col: 10, offset: 6081},
									val:        "s",
									ignoreCase: false,
									want:       "\"s\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 195, col: 5, offset: 6237},
						run: (*parser).callonEscape30,
						expr: &seqExpr{
							pos: position{line: 195, col: 5, offset: 6237},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 195, col: 5, offset: 6237},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 195, col: 10, offset: 6242},
									val:        "S",
									ignoreCase: false,
									want:       "\"S\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 198, col: 5, offset: 6411},
						run: (*parser).callonEscape34,
						expr: &seqExpr{
							pos: position{line: 198, col: 5, offset: 6411},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 198, col: 5, offset: 6411},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 198, col: 10, offset: 6416},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 201, col: 5, offset: 6499},
						run: (*parser).callonEscape38,
						expr: &seqExpr{
							pos: position{line: 201, col: 5, offset: 6499},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 201, col: 5, offset: 6499},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&litMatcher{
									pos:        position{line: 201, col: 10, offset: 6504},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 204, col: 5, offset: 6587},
						run: (*parser).callonEscape42,
						expr: &seqExpr{
							pos: position{line: 204, col: 5, offset: 6587},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 204, col: 5, offset: 6587},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&labeledExpr{
									pos:   position{line: 204, col: 10, offset: 6592},
									label: "char",
									expr: &ruleRefExpr{
										pos:  position{line: 204, col: 15, offset: 6597},
										name: "MetaChar",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Literal",
			pos:  position{line: 210, col: 1, offset: 6766},
			expr: &choiceExpr{
				pos: position{line: 210, col: 12, offset: 6777},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 210, col: 12, offset: 6777},
						run: (*parser).callonLiteral2,
						expr: &oneOrMoreExpr{
							pos: position{line: 210, col: 12, offset: 6777},
							expr: &ruleRefExpr{
								pos:  position{line: 210, col: 12, offset: 6777},
								name: "LiteralChars",
							},
						},
					},
					&actionExpr{
						pos: position{line: 212, col: 5, offset: 6848},
						run: (*parser).callonLiteral5,
						expr: &seqExpr{
							pos: position{line: 212, col: 5, offset: 6848},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 212, col: 5, offset: 6848},
									val:        "\\",
									ignoreCase: false,
									want:       "\"\\\\\"",
								},
								&labeledExpr{
									pos:   position{line: 212, col: 10, offset: 6853},
									label: "char",
									expr: &anyMatcher{
										line: 212, col: 15, offset: 6858,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LiteralChars",
			pos:  position{line: 219, col: 1, offset: 7112},
			expr: &charClassMatcher{
				pos:        position{line: 219, col: 17, offset: 7128},
				val:        "[a-zA-Z0-9_ !@#%&:;\"'<>,`~=/-]",
				chars:      []rune{'_', ' ', '!', '@', '#', '%', '&', ':', ';', '"', '\'', '<', '>', ',', '`', '~', '=', '/', '-'},
				ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Repeat",
			pos:  position{line: 223, col: 1, offset: 7246},
			expr: &actionExpr{
				pos: position{line: 223, col: 11, offset: 7256},
				run: (*parser).callonRepeat1,
				expr: &labeledExpr{
					pos:   position{line: 223, col: 11, offset: 7256},
					label: "spec",
					expr: &ruleRefExpr{
						pos:  position{line: 223, col: 16, offset: 7261},
						name: "RepeatSpec",
					},
				},
			},
		},
		{
			name: "RepeatSpec",
			pos:  position{line: 229, col: 1, offset: 7415},
			expr: &choiceExpr{
				pos: position{line: 229, col: 15, offset: 7429},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 229, col: 15, offset: 7429},
						run: (*parser).callonRepeatSpec2,
						expr: &litMatcher{
							pos:        position{line: 229, col: 15, offset: 7429},
							val:        "*",
							ignoreCase: false,
							want:       "\"*\"",
						},
					},
					&actionExpr{
						pos: position{line: 231, col: 5, offset: 7498},
						run: (*parser).callonRepeatSpec4,
						expr: &litMatcher{
							pos:        position{line: 231, col: 5, offset: 7498},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
					},
					&actionExpr{
						pos: position{line: 233, col: 5, offset: 7567},
						run: (*parser).callonRepeatSpec6,
						expr: &litMatcher{
							pos:        position{line: 233, col: 5, offset: 7567},
							val:        "?",
							ignoreCase: false,
							want:       "\"?\"",
						},
					},
					&actionExpr{
						pos: position{line: 235, col: 5, offset: 7635},
						run: (*parser).callonRepeatSpec8,
						expr: &seqExpr{
							pos: position{line: 235, col: 5, offset: 7635},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 235, col: 5, offset: 7635},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&litMatcher{
									pos:        position{line: 235, col: 9, offset: 7639},
									val:        ",",
									ignoreCase: false,
									want:       "\",\"",
								},
								&labeledExpr{
									pos:   position{line: 235, col: 13, offset: 7643},
									label: "max",
									expr: &oneOrMoreExpr{
										pos: position{line: 235, col: 17, offset: 7647},
										expr: &charClassMatcher{
											pos:        position{line: 235, col: 17, offset: 7647},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
								&litMatcher{
									pos:        position{line: 235, col: 24, offset: 7654},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 239, col: 5, offset: 7798},
						run: (*parser).callonRepeatSpec16,
						expr: &seqExpr{
							pos: position{line: 239, col: 5, offset: 7798},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 239, col: 5, offset: 7798},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&labeledExpr{
									pos:   position{line: 239, col: 9, offset: 7802},
									label: "min",
									expr: &oneOrMoreExpr{
										pos: position{line: 239, col: 13, offset: 7806},
										expr: &charClassMatcher{
											pos:        position{line: 239, col: 13, offset: 7806},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
								&litMatcher{
									pos:        position{line: 239, col: 20, offset: 7813},
									val:        ",",
									ignoreCase: false,
									want:       "\",\"",
								},
								&labeledExpr{
									pos:   position{line: 239, col: 24, offset: 7817},
									label: "max",
									expr: &oneOrMoreExpr{
										pos: position{line: 239, col: 28, offset: 7821},
										expr: &charClassMatcher{
											pos:        position{line: 239, col: 28, offset: 7821},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
								&litMatcher{
									pos:        position{line: 239, col: 35, offset: 7828},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 243, col: 5, offset: 7962},
						run: (*parser).callonRepeatSpec27,
						expr: &seqExpr{
							pos: position{line: 243, col: 5, offset: 7962},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 243, col: 5, offset: 7962},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&labeledExpr{
									pos:   position{line: 243, col: 9, offset: 7966},
									label: "min",
									expr: &oneOrMoreExpr{
										pos: position{line: 243, col: 13, offset: 7970},
										expr: &charClassMatcher{
											pos:        position{line: 243, col: 13, offset: 7970},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
								&litMatcher{
									pos:        position{line: 243, col: 20, offset: 7977},
									val:        ",",
									ignoreCase: false,
									want:       "\",\"",
								},
								&litMatcher{
									pos:        position{line: 243, col: 24, offset: 7981},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 246, col: 5, offset: 8083},
						run: (*parser).callonRepeatSpec35,
						expr: &seqExpr{
							pos: position{line: 246, col: 5, offset: 8083},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 246, col: 5, offset: 8083},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&labeledExpr{
									pos:   position{line: 246, col: 9, offset: 8087},
									label: "exact",
									expr: &oneOrMoreExpr{
										pos: position{line: 246, col: 15, offset: 8093},
										expr: &charClassMatcher{
											pos:        position{line: 246, col: 15, offset: 8093},
											val:        "[0-9]",
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
								&litMatcher{
									pos:        position{line: 246, col: 22, offset: 8100},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 251, col: 1, offset: 8198},
			expr: &notExpr{
				pos: position{line: 251, col: 8, offset: 8205},
				expr: &anyMatcher{
					line: 251, col: 9, offset: 8206,
				},
			},
		},
	},
}

func (c *current) onRoot1(regexp any) (any, error) {
	return regexp.(*ast.Regexp), nil
}

func (p *parser) callonRoot1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRoot1(stack["regexp"])
}

func (c *current) onRegexp1(first, rest any) (any, error) {
	matches := []*ast.Match{first.(*ast.Match)}
	if rest != nil {
		for _, r := range rest.([]any) {
			pair := r.([]any)
			matches = append(matches, pair[1].(*ast.Match))
		}
	}
	return &ast.Regexp{Matches: matches}, nil
}

func (p *parser) callonRegexp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRegexp1(stack["first"], stack["rest"])
}

func (c *current) onMatch1(frags any) (any, error) {
	fragments := []*ast.MatchFragment{}
	if frags != nil {
		for _, f := range frags.([]any) {
			fragments = append(fragments, f.(*ast.MatchFragment))
		}
	}
	return &ast.Match{Fragments: fragments}, nil
}

func (p *parser) callonMatch1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatch1(stack["frags"])
}

func (c *current) onMatchFragment1(content, repeat any) (any, error) {
	mf := &ast.MatchFragment{Content: content.(ast.Node)}
	if repeat != nil {
		mf.Repeat = repeat.(*ast.Repeat)
	}
	return mf, nil
}

func (p *parser) callonMatchFragment1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMatchFragment1(stack["content"], stack["repeat"])
}

func (c *current) onAnchor1() (any, error) {
	anchorType := "start"
	if string(c.text) == "$" {
		anchorType = "end"
	}
	return &ast.Anchor{AnchorType: anchorType}, nil
}

func (p *parser) callonAnchor1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnchor1()
}

func (c *current) onSubexp1(regexp any) (any, error) {
	s := &ast.Subexp{
		GroupType: "capture",
		Number:    parserState(c).NextGroupNumber(),
		Regexp:    regexp.(*ast.Regexp),
	}
	return s, nil
}

func (p *parser) callonSubexp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSubexp1(stack["regexp"])
}

func (c *current) onBackReference1(num any) (any, error) {
	n := int(num.([]byte)[0] - '0')
	return &ast.BackReference{Number: n}, nil
}

func (p *parser) callonBackReference1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBackReference1(stack["num"])
}

func (c *current) onCharset1(inverted, items any) (any, error) {
	charset := &ast.Charset{
		Inverted: inverted != nil,
		Items:    []ast.CharsetItem{},
	}
	if items != nil {
		for _, item := range items.([]any) {
			charset.Items = append(charset.Items, item.(ast.CharsetItem))
		}
	}
	return charset, nil
}

func (p *parser) callonCharset1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharset1(stack["inverted"], stack["items"])
}

func (c *current) onPOSIXClass2(name any) (any, error) {
	return &ast.POSIXClass{Name: name.(string), Negated: false}, nil
}

func (p *parser) callonPOSIXClass2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClass2(stack["name"])
}

func (c *current) onPOSIXClass8(name any) (any, error) {
	// Some implementations support negated POSIX classes [:^alpha:]
	return &ast.POSIXClass{Name: name.(string), Negated: true}, nil
}

func (p *parser) callonPOSIXClass8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClass8(stack["name"])
}

func (c *current) onPOSIXClassName2() (any, error) {
	return "alnum", nil
}

func (p *parser) callonPOSIXClassName2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClassName2()
}

func (c *current) onPOSIXClassName4() (any, error) {
	return "alpha", nil
}

func (p *parser) callonPOSIXClassName4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClassName4()
}

func (c *current) onPOSIXClassName6() (any, error) {
	return "blank", nil
}

func (p *parser) callonPOSIXClassName6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClassName6()
}

func (c *current) onPOSIXClassName8() (any, error) {
	return "cntrl", nil
}

func (p *parser) callonPOSIXClassName8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClassName8()
}

func (c *current) onPOSIXClassName10() (any, error) {
	return "digit", nil
}

func (p *parser) callonPOSIXClassName10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClassName10()
}

func (c *current) onPOSIXClassName12() (any, error) {
	return "graph", nil
}

func (p *parser) callonPOSIXClassName12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClassName12()
}

func (c *current) onPOSIXClassName14() (any, error) {
	return "lower", nil
}

func (p *parser) callonPOSIXClassName14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClassName14()
}

func (c *current) onPOSIXClassName16() (any, error) {
	return "print", nil
}

func (p *parser) callonPOSIXClassName16() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClassName16()
}

func (c *current) onPOSIXClassName18() (any, error) {
	return "punct", nil
}

func (p *parser) callonPOSIXClassName18() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClassName18()
}

func (c *current) onPOSIXClassName20() (any, error) {
	return "space", nil
}

func (p *parser) callonPOSIXClassName20() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClassName20()
}

func (c *current) onPOSIXClassName22() (any, error) {
	return "upper", nil
}

func (p *parser) callonPOSIXClassName22() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClassName22()
}

func (c *current) onPOSIXClassName24() (any, error) {
	return "xdigit", nil
}

func (p *parser) callonPOSIXClassName24() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPOSIXClassName24()
}

func (c *current) onCharsetRange1(first, last any) (any, error) {
	return &ast.CharsetRange{
		First: first.(string),
		Last:  last.(string),
	}, nil
}

func (p *parser) callonCharsetRange1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetRange1(stack["first"], stack["last"])
}

func (c *current) onCharsetRangeEscape1(char any) (any, error) {
	return string(char.([]byte)), nil
}

func (p *parser) callonCharsetRangeEscape1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetRangeEscape1(stack["char"])
}

func (c *current) onCharsetRangeLiteral1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCharsetRangeLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetRangeLiteral1()
}

func (c *current) onCharsetEscape1(char any) (any, error) {
	return &ast.CharsetLiteral{Text: string(char.([]byte))}, nil
}

func (p *parser) callonCharsetEscape1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetEscape1(stack["char"])
}

func (c *current) onCharsetLiteral2() (any, error) {
	return &ast.CharsetLiteral{Text: string(c.text)}, nil
}

func (p *parser) callonCharsetLiteral2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetLiteral2()
}

func (c *current) onCharsetLiteral4(char any) (any, error) {
	// Unknown escape in charset - treat as literal (be lenient)
	return &ast.CharsetLiteral{Text: string(char.([]byte))}, nil
}

func (p *parser) callonCharsetLiteral4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharsetLiteral4(stack["char"])
}

func (c *current) onAnyChar1() (any, error) {
	return &ast.AnyCharacter{}, nil
}

func (p *parser) callonAnyChar1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnyChar1()
}

func (c *current) onEscape2() (any, error) {
	// Word start anchor (GNU extension)
	return &ast.Anchor{AnchorType: "word_start"}, nil
}

func (p *parser) callonEscape2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape2()
}

func (c *current) onEscape6() (any, error) {
	// Word end anchor (GNU extension)
	return &ast.Anchor{AnchorType: "word_end"}, nil
}

func (p *parser) callonEscape6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape6()
}

func (c *current) onEscape10() (any, error) {
	// Word boundary (GNU extension)
	return &ast.Anchor{AnchorType: "word_boundary"}, nil
}

func (p *parser) callonEscape10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape10()
}

func (c *current) onEscape14() (any, error) {
	// Non-word boundary (GNU extension)
	return &ast.Anchor{AnchorType: "non_word_boundary"}, nil
}

func (p *parser) callonEscape14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape14()
}

func (c *current) onEscape18() (any, error) {
	// Word character (GNU extension) - synonym for [_[:alnum:]]
	return &ast.Escape{EscapeType: "word", Code: "w", Value: "word character"}, nil
}

func (p *parser) callonEscape18() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape18()
}

func (c *current) onEscape22() (any, error) {
	// Non-word character (GNU extension) - synonym for [^_[:alnum:]]
	return &ast.Escape{EscapeType: "non_word", Code: "W", Value: "non-word character"}, nil
}

func (p *parser) callonEscape22() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape22()
}

func (c *current) onEscape26() (any, error) {
	// Whitespace (GNU extension) - synonym for [[:space:]]
	return &ast.Escape{EscapeType: "whitespace", Code: "s", Value: "whitespace"}, nil
}

func (p *parser) callonEscape26() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape26()
}

func (c *current) onEscape30() (any, error) {
	// Non-whitespace (GNU extension) - synonym for [^[:space:]]
	return &ast.Escape{EscapeType: "non_whitespace", Code: "S", Value: "non-whitespace"}, nil
}

func (p *parser) callonEscape30() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape30()
}

func (c *current) onEscape34() (any, error) {
	// Literal ] (GNU extension)
	return &ast.Literal{Text: "]"}, nil
}

func (p *parser) callonEscape34() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape34()
}

func (c *current) onEscape38() (any, error) {
	// Literal } (GNU extension)
	return &ast.Literal{Text: "}"}, nil
}

func (p *parser) callonEscape38() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape38()
}

func (c *current) onEscape42(char any) (any, error) {
	// Escaped metacharacter becomes literal
	return &ast.Literal{Text: string(char.([]byte))}, nil
}

func (p *parser) callonEscape42() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape42(stack["char"])
}

func (c *current) onLiteral2() (any, error) {
	return &ast.Literal{Text: string(c.text)}, nil
}

func (p *parser) callonLiteral2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLiteral2()
}

func (c *current) onLiteral5(char any) (any, error) {
	// Unknown escape - undefined behavior per GNU docs, treat as literal
	return &ast.Literal{Text: string(char.([]byte))}, nil
}

func (p *parser) callonLiteral5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLiteral5(stack["char"])
}

func (c *current) onRepeat1(spec any) (any, error) {
	return spec.(*ast.Repeat), nil
}

func (p *parser) callonRepeat1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeat1(stack["spec"])
}

func (c *current) onRepeatSpec2() (any, error) {
	return &ast.Repeat{Min: 0, Max: -1, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec2()
}

func (c *current) onRepeatSpec4() (any, error) {
	return &ast.Repeat{Min: 1, Max: -1, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec4()
}

func (c *current) onRepeatSpec6() (any, error) {
	return &ast.Repeat{Min: 0, Max: 1, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec6()
}

func (c *current) onRepeatSpec8(max any) (any, error) {
	// GNU extension: {,m} means at most m
	maxVal := parseInt(max)
	return &ast.Repeat{Min: 0, Max: maxVal, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec8(stack["max"])
}

func (c *current) onRepeatSpec16(min, max any) (any, error) {
	minVal := parseInt(min)
	maxVal := parseInt(max)
	return &ast.Repeat{Min: minVal, Max: maxVal, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec16() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec16(stack["min"], stack["max"])
}

func (c *current) onRepeatSpec27(min any) (any, error) {
	minVal := parseInt(min)
	return &ast.Repeat{Min: minVal, Max: -1, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec27() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec27(stack["min"])
}

func (c *current) onRepeatSpec35(exact any) (any, error) {
	val := parseInt(exact)
	return &ast.Repeat{Min: val, Max: val, Greedy: true}, nil
}

func (p *parser) callonRepeatSpec35() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRepeatSpec35(stack["exact"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
